apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: gcr.io/jenkinsx-dev/jenkins-jstrachan
    dockerfilePath: Dockerfile.tmp
    workspace: .
  googleCloudBuild:
    projectId: jenkinsx-dev
deploy:
  kubectl:
    manifests:
    - k8s-*